# Generated by Django 3.2.8 on 2021-12-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strReq', models.CharField(max_length=255)),
                ('strRes', models.IntegerField(null=True)),
                ('dtCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
